import jsPDF from 'jspdf';
import { formatDate } from './dateUtils';

/**
 * Generate a PDF from a weekly report.
 */
export function generateReportPDF({ studentName, weekLabel, narrative, highlights, activities }) {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Header
  pdf.setFillColor(91, 79, 207);
  pdf.rect(0, 0, pageWidth, 40, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(22);
  pdf.setFont('helvetica', 'bold');
  pdf.text('DyslexiaEd', margin, 18);

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Weekly Progress Report', margin, 28);
  pdf.text(weekLabel || formatDate(new Date()), pageWidth - margin, 28, { align: 'right' });

  y = 55;

  // Student name
  pdf.setTextColor(26, 26, 46);
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`Report for ${studentName || 'Student'}`, margin, y);
  y += 12;

  // Narrative
  if (narrative) {
    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(60, 60, 80);

    const lines = pdf.splitTextToSize(narrative, contentWidth);
    lines.forEach((line) => {
      if (y > 270) {
        pdf.addPage();
        y = margin;
      }
      pdf.text(line, margin, y);
      y += 6;
    });
    y += 8;
  }

  // Handwriting highlights
  if (highlights) {
    pdf.setFontSize(13);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(26, 26, 46);
    pdf.text('Handwriting Highlights', margin, y);
    y += 8;

    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(60, 60, 80);

    const hLines = pdf.splitTextToSize(highlights, contentWidth);
    hLines.forEach((line) => {
      if (y > 270) {
        pdf.addPage();
        y = margin;
      }
      pdf.text(line, margin, y);
      y += 6;
    });
    y += 8;
  }

  // Recommended activities
  if (activities && activities.length > 0) {
    pdf.setFontSize(13);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(26, 26, 46);
    pdf.text('Recommended Activities', margin, y);
    y += 8;

    pdf.setFontSize(11);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(60, 60, 80);

    activities.forEach((activity, i) => {
      if (y > 270) {
        pdf.addPage();
        y = margin;
      }
      const text = `${i + 1}. ${activity}`;
      const lines = pdf.splitTextToSize(text, contentWidth - 5);
      lines.forEach((line) => {
        pdf.text(line, margin + 3, y);
        y += 6;
      });
      y += 2;
    });
  }

  // Footer
  const totalPages = pdf.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 160);
    pdf.text(
      `Generated by DyslexiaEd • ${formatDate(new Date())} • Page ${i} of ${totalPages}`,
      pageWidth / 2,
      290,
      { align: 'center' }
    );
  }

  return pdf;
}

export function downloadReportPDF(reportData) {
  const pdf = generateReportPDF(reportData);
  const filename = `dyslexiaed-report-${reportData.studentName || 'student'}-${Date.now()}.pdf`;
  pdf.save(filename);
}
